export enum BodyRegionEnum {
	NECK = 'neck',
	SHOULDER = 'shoulder',
	UPPER_BACK = 'upper_back',
	LOWER_BACK = 'lower_back',
	CHEST = 'chest',
	ARM = 'arm',
	ELBOW = 'elbow',
	WRIST = 'wrist',
	HAND = 'hand',
	HIP = 'hip',
	THIGH = 'thigh',
	KNEE = 'knee',
	CALF = 'calf',
	ANKLE = 'ankle',
	FOOT = 'foot',
	CORE = 'core',
	FULL_BODY = 'full_body',
}
